- Python에서 행렬(Matrix)를 효과적으로 사용하기 위한 외부 라이브러리로 행렬과 관련된 다양한 기능을 가지고 있어, 처리/분석에 적합

- Numpy 내부 알고리즘은 C 언어로 작성되어, 적은 메모리로 빠른 처리가 가능

- 배열(Array)이 가진 요소(Elements)에 각각 2를 곱하고 이를 저장한 새로운 배열을 만드는 시간 측정 => Numpy를 사용한 경우가 더 빠른 것 확인할 수 있음

In [ ]:
import numpy as np

In [ ]:
#ndarray형 객체와 list형 객체 생성
np_arr = np.arange(1000000)
list_arr = list(range(1000000))

In [ ]:
#1000000의 요소에 곱하기 2하는 과정을 10번 수행
#%time 은 코드 한 줄이 실행하는데 걸리는 시간 출력
%time for _ in range(10): my_arr = np_arr *2
%time for _ in range(10): my_arr = [x * 2 for x in list_arr]

CPU times: user 14.6 ms, sys: 6.21 ms, total: 20.8 ms
Wall time: 24.5 ms
CPU times: user 798 ms, sys: 178 ms, total: 975 ms
Wall time: 976 ms


- ndarray는 Numpy의 기본 객체
- 다차원 배열을 빨리 처리하기 위해 homogeneous array(동종 배열) => 배열과 종류 하나로 통일


In [ ]:
#기본적인 객체 ndarray 만들기
print(type(np.array(1)))
print(type(np.array(0.1)))
print(type(np.array("str")))
print(type(np.array(True)))
print(type(np.array(["list"])))
print(type(np.array(("tuple"))))
print(type(np.array(({"key":"value"}))))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
#2행 3열의 난수로 구성된 객체 ndarray 만들기
rand_data = np.random.randn(2, 3)
print(rand_data, "\n")

#산술연산도 가능
print(rand_data * 10, "\n")
print(rand_data + rand_data, "\n")

[[-0.36523756  1.69719281  1.22487174]
 [ 0.98221423  0.07596641  0.01387814]] 

[[-3.6523756  16.97192809 12.24871736]
 [ 9.82214225  0.7596641   0.13878136]] 

[[-0.73047512  3.39438562  2.44974347]
 [ 1.96442845  0.15193282  0.02775627]] 



In [ ]:
#객체 ndarray의 Attribute(Instance Variable)
print(type(rand_data))
print(rand_data.shape) #ndarray의 각 차원을 정수 혹은 정수형으로 구성된 튜플로 알려줌
print(rand_data.ndim) #ndarray가 총 몇 차원으로 구성되었는지 알려줌
print(rand_data.dtype) #ndarray가 어떠한 자료형으로 구성되었는지 알려줌

<class 'numpy.ndarray'>
(2, 3)
2
float64


In [ ]:
#자료형 list와 객체 ndarray의 출력 비교
list_arr = [[1,2,3,], [4,5,6]]
print(list_arr)
print(type(list_arr))

np_arr = np.array([[1,2,3,], [4,5,6]])
print(np_arr)
print(type(np_arr))

print(np_arr.ndim)
print(np_arr.shape)
print(np_arr.shape[0]) #자료형이 tuple이기 때문에 불러올 수 있음
print(np_arr.shape[1]) 
print(np_arr.dtype)

[[1, 2, 3], [4, 5, 6]]
<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)
2
3
int64


In [ ]:
#다른 자료형이 섞여있는 경우 = > 오류 X, 더 많은 것을 표현할 수 있는 자료형으로 통일
#string의 경우 가장 긴 문자열로 통일 
list_arr = [[1.0, 2.0, 3.0], [4,5,6]]
np_arr = np.array(list_arr)
print(np_arr.dtype)

float64


In [ ]:
#복잡한 ndarray 객체 만들기(array, arange, ones, ones_like)
my_data = np.array([1,2,3])
print(my_data, my_data.shape)

#.arange(start, stop, step)
my_data = np.arange(3, 0, -1)
print(my_data, my_data.shape)

#행렬의 크기 넣어주면 크기만큼 1로 채움
my_data = np.ones(3)
print(my_data, my_data.shape)

#어떤 값을 채웠는지 중요 X, 몇행 몇열인지 분석 후 동일한 크기로 출력
my_data = np.ones_like([5, 4, 3, 2, 1, 0])
print(my_data, my_data.shape)

[1 2 3] (3,)
[3 2 1] (3,)
[1. 1. 1.] (3,)
[1 1 1 1 1 1] (6,)


In [ ]:
#복잡한 ndarray 객체 만들기(zeros, zeros_like, full, full_like)
#.ones와 동일 대신 0으로 채움
my_data = np.zeros(3)
print(my_data, my_data.shape)

#.ones_like와 동일 대신 0으로 채움
my_data = np.zeros_like([5, 4, 3, 2, 1, 0])
print(my_data, my_data.shape)

#.full((4, 2, 4,), True) => 4층 2행 4열을 True로 채움
my_data = np.full((4,2,4,), True)
print(my_data, my_data.shape, my_data.dtype)

my_data = np.full_like(list_arr, True) #list_arr: 2 X 3 행렬
print(my_data, my_data.shape, my_data.dtype)

[0. 0. 0.] (3,)
[0 0 0 0 0 0] (6,)
[[[ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]]] (4, 2, 4) bool
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) float64


그 외의 방법
- np.empty(), np.empty_like => 값이 없는 행렬
- np.assaray() => 자료형으로 변환
-  np.eye(), np.identity() => 단위 행렬

In [ ]:
#객체 ndarray의 자료형을 변환해야 할 경우 .astype() 사용
#실수형을 정수형을 바꾸어 소수점 이하를 버릴 때, 불러온 문자열을 실수/정수형으로 바꿀 때
#변환에 실패할 경우, ValueError 발생
int_arr = np.array([1, 2, 3, 4, 5])
print(int_arr, int_arr.dtype)

#np.astype() X, ndarray.astype() O
float_arr = int_arr.astype(np.float64) 
print(float_arr, float_arr.dtype)

#가장 긴 문자열로 통일 => .dtype 출력시 S와 통일된 최대값이 나옴 
string_arr = np.array(['+1.25', '-9.7', '43'], dtype=np.string_)
print(string_arr, string_arr.dtype)

string_to_float_arr = string_arr.astype(float)
print(string_to_float_arr, string_to_float_arr.dtype)

[1 2 3 4 5] int64
[1. 2. 3. 4. 5.] float64
[b'+1.25' b'-9.7' b'43'] |S5
[ 1.25 -9.7  43.  ] float64


In [ ]:
#Broadcasting - 벡터화(Vectorization)
#Numpy는 for 반복문 없이 연산 가능
#list의 덧셈 연산은 list를 합침, ndarray의 덧셈 연산은 행렬을 덧셈 연산
full_data = np.full((4,5), 2)
print(full_data)

print(full_data + full_data)
print(full_data - full_data)
print(full_data * full_data)

#행렬에 스칼라(Scala)를 연산할 경우
print(full_data * 1.5)
print(full_data / 2)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Broadcasting - 서로 다른 두 행렬의 비교 연산 => True, False로 출력
np_arr = np.array([[1, 3, 5], [2, 4, 6]])
np_arr2 = np.array([[-2, 3, -1], [4, 8, -12]])


print(np_arr < np_arr2)
print(np_arr > np_arr2)
#행의 크기가 다른 경우 => 자동으로 확장 시켜서 연산 수행 
print(np_arr <= np.array([[4], [4]]))

[[False False False]
 [ True  True False]]
[[ True False  True]
 [False False  True]]
[[ True  True False]
 [ True  True False]]


ufunc(유니버셜 함수 - universal function)
- 객체 ndarray를 연산하기 위한 메소드
  - sqrt, square, exp, ceil, floor (매개변수 1개)
  - add, substract, multiply, divide, floor_divide(매개변수 2개)


In [ ]:
#1차원에서의 indexing과 slicing
#객체 ndarray의 일부를 선택할 경우
arange_data = np.arange(10)
list_data = list(range(10))

print(arange_data)
print(list_data)

print(arange_data[3])
print(list_data[3])
print(arange_data[2:7])
print(list_data[2:7])

[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
3
3
[2 3 4 5 6]
[2, 3, 4, 5, 6]


In [ ]:
#다차원에서의 indexing과 slicing
#객체 ndarray의 일부를 선택할 경우
arange_array = np.array([np.arange(0, 4), np.arange(4,8), np.arange(8,12), np.arange(12,16)])
print("전체 array 출력")
print(arange_array, "\n")

print(arange_array[0][1])
print(arange_array[0, 1], "\n")

#첫번째 행 출력하기
print("첫 번째 행 출력")
print(arange_array[0]) 
print(arange_array[0][:])
print(arange_array[0, ], "\n")

print("slicing 연습1")
print(arange_array[:3, 1:], "\n") #0~2번 행에서 1~마지막 열 출력

print("slicing 연습2")
#둘 다 의미하는 바는 마지막 열 전체를 말함
print(arange_array[:, 3], "\n") #1차원(가로) 출력, 재정렬해서 하나의 행렬로 출력
print(arange_array[:, 3:4], "\n") #원본 값 처럼 출력하고 싶은 경우

print("slicing 연습3")
print(arange_array[1, :3]) #1번째 행에서 0~2번 열 출력

전체 array 출력
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

1
1 

첫 번째 행 출력
[0 1 2 3]
[0 1 2 3]
[0 1 2 3] 

slicing 연습1
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]] 

slicing 연습2
[ 3  7 11 15] 

[[ 3]
 [ 7]
 [11]
 [15]] 

slicing 연습3
[4 5 6]


In [ ]:
#indexing과 slicing에서 한 일부 행렬의 값을 바꿀 때
print("자료형 list")
print(list_data)
for x in range(2, 7):
  list_data[x] = -1
print(list_data, type(list_data), "\n")

print("객체 ndarray 1차원")
print(arange_data)
arange_data[2:7] = -1
print(arange_data, arange_data.dtype, "\n")

print("객체 ndarray 2차원")
print(arange_array)
arange_array[1, :2] = -1
print(arange_array, arange_array.dtype, "\n")

자료형 list
[0, 1, -1, -1, -1, -1, -1, 7, 8, 9]
[0, 1, -1, -1, -1, -1, -1, 7, 8, 9] <class 'list'> 

객체 ndarray 1차원
[[ 0  1  2  3]
 [ 4  5  6  7]
 [-1  9 -1 -1]
 [-1  9 -1 -1]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]] int64 

객체 ndarray 2차원
[[ 0  1  2  3]
 [-1 -1  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [-1 -1  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] int64 



In [ ]:
#list의 경우 복제 ndarray의 경우 가르키기(view) 때문에 수정시 원본 데이터가 바뀜
arange2_data = arange_data[2]
print(arange2_data)
list2_data = list_data[3:6]
print(list2_data)

arange2_data[1] = 9
list2_data[1] = 9

print(arange_data) #slicing한 행렬 변경한 경우 원본 데이터도 바뀜
print(list_data) #slicing한 행렬 변경해도 원본 데이터는 바뀌지 않음
print(arange2_data)
print(list2_data)

[-1 -1 -1 -1]
[-1, -1, -1]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [-1  9 -1 -1]
 [-1 -1 -1 -1]]
[0, 1, -1, -1, -1, -1, -1, 7, 8, 9]
[-1  9 -1 -1]
[-1, 9, -1]


In [ ]:
#list와 ndarray의 행렬을 slicing 한 후 slicing한 행렬을 변경한 때 원본 데이터도 바뀌는지 확인
list_data = list(range(10))
list2_data = list_data[3:6]
print(list2_data)
list2_data[1] = -1
print(list2_data)
print(list_data, "\n")

arange_data = np.arange(10)
arange2_data = arange_data[3:6]
print(arange2_data)
arange2_data[1] = -1
print(arange2_data)
print(arange_data)

[3, 4, 5]
[3, -1, 5]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 

[3 4 5]
[ 3 -1  5]
[ 0  1  2  3 -1  5  6  7  8  9]


In [ ]:
#다차원 또한 동일함
print(arange_array)
arange_array[1, :2] = -1
print(arange_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [-1 -1  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
#유사한 경우 => 바뀌는 것 확인 가능
n_data = np.array([0,25, 0.5, 0.75, 1.0, 1.25])
m_data = [n_data, n_data, n_data]
print(m_data)

n_data[0] = -1
print(m_data)

#but 둘 다 ndarray의 경우 안바뀜
n_data = np.array([0,25, 0.5, 0.75, 1.0, 1.25])
m_data = np.array([n_data, n_data, n_data])
print(m_data)

n_data[0] = -1
print(m_data)

[array([ 0.  , 25.  ,  0.5 ,  0.75,  1.  ,  1.25]), array([ 0.  , 25.  ,  0.5 ,  0.75,  1.  ,  1.25]), array([ 0.  , 25.  ,  0.5 ,  0.75,  1.  ,  1.25])]
[array([-1.  , 25.  ,  0.5 ,  0.75,  1.  ,  1.25]), array([-1.  , 25.  ,  0.5 ,  0.75,  1.  ,  1.25]), array([-1.  , 25.  ,  0.5 ,  0.75,  1.  ,  1.25])]
[[ 0.   25.    0.5   0.75  1.    1.25]
 [ 0.   25.    0.5   0.75  1.    1.25]
 [ 0.   25.    0.5   0.75  1.    1.25]]
[[ 0.   25.    0.5   0.75  1.    1.25]
 [ 0.   25.    0.5   0.75  1.    1.25]
 [ 0.   25.    0.5   0.75  1.    1.25]]


In [ ]:
#.reshape() 생성한 객체 ndarray의 차원 구조 변경
one_data = np.ones(15).reshape(3, 5)
print(one_data, one_data.shape, "\n")
arange_data = np.arange(15).reshape(one_data.shape) #차원만 전달해줘도 괜찮음
print(arange_data, arange_data.shape, "\n")

#아래 결과는 모두 동일
print(np.reshape(arange_data, (5, 3)), arange_data.shape, "\n")
print(arange_data.reshape((5, 3)), arange_data.shape, "\n")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (3, 5) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5) 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] (3, 5) 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] (3, 5) 



In [ ]:
#변경된 행렬 구조 반영 필수
arange_data = arange_data.reshape((5, 3))
print(arange_data)
print(arange_data.shape)

#차원 정보가 -1인 경우, 적절한 차원으로 자동 생성
arange_data = np.arange(24).reshape((2, 4, -1))
print(arange_data.shape)

arange_dat = np.arange(24).reshape((2, -1, 3))
print(arange_data.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
(5, 3)
(2, 4, 3)
(2, 4, 3)


In [ ]:
#다차원의 객체 ndarray를 1차원으로 일괄 변경
arange_data = np.arange(15).reshape(3,5)
print(arange_data, arange_data.shape, "\n")

arange_data2 = np.ravel(arange_data)
print(arange_data2, arange_data2.shape, "\n")

#가리키기 때문에 원본 데이터에도 영향이 감
arange_data2[0] = -1
print(arange_data, arange_data.shape)
print(arange_data2, arange_data2.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] (15,) 

[[-1  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)
[-1  1  2  3  4  5  6  7  8  9 10 11 12 13 14] (15,)


In [ ]:
#메소트 flatten은 새로운 객체 ndarray를 생성
arange_data = np.arange(15).reshape(3,5)
arange_data2 = arange_data.flatten()

print(arange_data2, arange_data2.shape, "\n")

#flatten을 사용한 경우 원본 데이터 바뀌지 않음
arange_data2[0] = -1
print(arange_data, arange_data.shape)
print(arange_data2, arange_data2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] (15,) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)
[-1  1  2  3  4  5  6  7  8  9 10 11 12 13 14] (15,)


In [ ]:
#.concatenate : 매개변수로 전달받은 축 정보로 합침(axis = 0 : 행으로 추가 / 1 : 열로 추가)
#.vstack : 행으로 합침(세로)
#.hstack : 열로 합침(가로)
#행으로 추가하기
data1 = np.arange(0, 15).reshape(3,5)
data2 = np.arange(15, 30).reshape(3,5)

#아래 결과는 동일하게 나옴
print(np.concatenate([data1, data2], 0))
print(np.vstack((data1, data2)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:
#열로 추가하기
print(np.concatenate([data1, data2], 1))
print(np.hstack((data1, data2)))

[[ 0  1  2  3  4 15 16 17 18 19]
 [ 5  6  7  8  9 20 21 22 23 24]
 [10 11 12 13 14 25 26 27 28 29]]
[[ 0  1  2  3  4 15 16 17 18 19]
 [ 5  6  7  8  9 20 21 22 23 24]
 [10 11 12 13 14 25 26 27 28 29]]


In [ ]:
#ndarray의 차원을 분리하기
#sacala 형태 : 동일한 크기의 차원으로 scals개로 분리(동일한 크기로 분리 못하면 ValueError 발생)
#range gudxo : 총 3개로 분리하며 중간 Index 값을 입력(범위를 벗어나면 비어있는 행렬 반환)
arange_data = np.arange(30).reshape(6, 5)
print(arange_data)

#axis = 0 : 행으로 쪼개기, 1: 열로 쪼개기
print(np.split(arange_data, 3), "\n")
print(np.split(arange_data, [2,3], 0), '\n')
print(np.split(arange_data, [2,3], 1), "\n")
print("")
#default인 3개로 쪼갤꺼고 넣은 값이 중앙 값이기에 뒤에 값이 없어서 빈 array도 나옴
print(np.split(arange_data,[2,6]))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])] 

[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])] 

[array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21],
       [25, 26]]), array([[ 2],
       [ 7],
       [12],
       [17],
       [22],
       [27]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24],
       [28, 29]])] 


[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]]), array([], shape=(0, 5), dtype=int64)]


In [ ]:
#vsplit : 행(가로)으로 분리
print("원본 데이터")
arange_data = np.arange(30).reshape(6, 5)
print(arange_data, "\n")

print("vsplit 사용")
print(np.vsplit(arange_data, 3), "\n") #3개 행으로 분리
print(np.vsplit(arange_data, [2, 3]), "\n") #2,3번 행을 중간 index로 지정
print(np.vsplit(arange_data, [2, 5]), "\n") #2,3,4,번 행을 중간 index로 지정 
print(np.vsplit(arange_data, [2, 6]), "\n") #2,3,4,5 번 행을 중간 index로 지정, 뒤에 행 없으면 빈 행렬 반환 

원본 데이터
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 

vsplit 사용
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])] 

[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])] 

[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29]])] 

[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]]), array([], shape=(0, 5), dtype=int64)] 



In [ ]:
#hsplit : 열(세로)로 분리
print("hsplit 사용")
print(arange_data)
print(np.split(arange_data, 5, 1)) #axis = 1 열 방향으로 5등분
print(np.hsplit(arange_data, 5)) #3번 열을 중간 index로 지정
print(np.hsplit(arange_data, [1, 2])) #1번 열을 중간 indxe로 지정
print(np.hsplit(arange_data, [1, 3])) #1,2 번 열을 중간 indxe로 지정

hsplit 사용
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25]]), array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]]), array([[ 2],
       [ 7],
       [12],
       [17],
       [22],
       [27]]), array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28]]), array([[ 4],
       [ 9],
       [14],
       [19],
       [24],
       [29]])]
[array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25]]), array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]]), array([[ 2],
       [ 7],
       [12],
       [17],
       [22],
       [27]]), array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28]]), array([[ 4],
       [ 9],
       [14],
       [19],
       [24],
       [29]])]
[array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25]])

In [ ]:
#repeat : 행렬을 반복, scala 형태만 가능
arange_data = np.arange(5)
print(arange_data)

#5번씩 반복
print(np.repeat(arange_data, 5))

#각 요소별 다르게 반복
print(np.repeat(arange_data, [1, 1, 3, 2, 1]))
print(np.repeat(arange_data, [0, 0, 3, 0, 0]))

[0 1 2 3 4]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4]
[0 1 2 2 2 3 3 4]
[2 2 2]


In [ ]:
#tile : 행렬 자체 행 혹은 열 방향으로 반복, shape처럼 배열 형태로 전달 가능
print(np.tile(arange_data, 2))
print(np.tile(arange_data, (1, 3)))
print(np.tile(arange_data, (3, 1)))

[0 1 2 3 4 0 1 2 3 4]
[[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
#다차원 행렬에서의 반복
arange_data = np.arange(15).reshape((3, 5))
print(np.repeat(arange_data, 2), "\n") #다차원 행렬에서 메소드 repeat는 축 정보가 없으면 평탄화 발생

print(np.repeat(arange_data, 2, 0)) #axis = 0 : 행 방향 추가
print(np.repeat(arange_data, 2, 1), "\n") #axis = 1 : 열 방향 추가

print(np.tile(arange_data, 2), "\n") #전체 반복
print(np.tile(arange_data, (1, 3)), "\n")
print(np.tile(arange_data, (3, 2)))

[ 0  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10 10 11 11
 12 12 13 13 14 14] 

[[ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [10 11 12 13 14]]
[[ 0  0  1  1  2  2  3  3  4  4]
 [ 5  5  6  6  7  7  8  8  9  9]
 [10 10 11 11 12 12 13 13 14 14]] 

[[ 0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]] 

[[ 0  1  2  3  4  0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14 10 11 12 13 14]] 

[[ 0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]
 [ 0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]
 [ 0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]]


In [ ]:
#indexing / slicing 확장
#데이터 수가 많아, 출력화면의 가로축이 협소할 수 있음 => 가로축 무제한으로 늘리는 방법
import numpy as np
np.set_printoptions(linewidth=np.inf) #무제한으로 설정
np.set_printoptions(linewidth=75) #default는 75

In [ ]:
man_name = ['월화', '지빈', '하람', '지환', '명환', '진호']
woman_name = ['보경', '연지', '예담', '유리', '이령', '다희']

name_arr = np.array(['지빈', '명환', '연지', '하람', '연지', '진호', '월하', '연지'])
data_arr = np.random.randn(8, 4)

print(name_arr)
print(data_arr)

['지빈' '명환' '연지' '하람' '연지' '진호' '월하' '연지']
[[-0.29328103 -0.22242053  0.54910688  0.91494522]
 [ 0.2863458  -0.05648714 -1.76886857  0.32965203]
 [ 1.45282117 -0.48131736 -0.11466913 -0.87196527]
 [-0.48235925  0.66061707  1.16550195 -1.2294553 ]
 [ 0.24536411  0.89414005 -0.30706926  1.31847257]
 [-0.22343436  1.09889078 -0.59373514  0.68180308]
 [ 1.38830303 -1.11068124 -0.86322786  1.37884826]
 [-0.04764955 -0.31243761 -0.52817884 -0.21344169]]
[False False  True False  True False False  True]


In [ ]:
#index = 3,5,8은 True
print(name_arr == '연지')

[False False  True False  True False False  True]


In [ ]:
#True인 배열의 행(row) 전체 출력
print(data_arr[name_arr == '연지'])

[[ 1.45282117 -0.48131736 -0.11466913 -0.87196527]
 [ 0.24536411  0.89414005 -0.30706926  1.31847257]
 [-0.04764955 -0.31243761 -0.52817884 -0.21344169]]


In [ ]:
print(data_arr[name_arr == "연지", 2:], "\n") #True 중 2~마짐막 열까지
print(data_arr[name_arr == '연지', 3], "\n") #True 중 마지막 열 하나의 배열로
print(data_arr[name_arr == '연지', 3:4]) #True 중 마지막 열 원본 그대로

[[-0.11466913 -0.87196527]
 [-0.30706926  1.31847257]
 [-0.52817884 -0.21344169]] 

[-0.87196527  1.31847257 -0.21344169] 

[[-0.87196527]
 [ 1.31847257]
 [-0.21344169]]


In [ ]:
#and / or 연산의 경우 주소에 바로 입력할 수 없음
or_opp = (name_arr == '지빈') | (name_arr == '월하')
print(or_opp)
print(data_arr[or_opp])
print("")
#not 연산은 ~로 활용
not_opp = ~(name_arr == '하람')
print(not_opp)
print(data_arr[not_opp])

[ True False False False False False  True False]
[[-0.29328103 -0.22242053  0.54910688  0.91494522]
 [ 1.38830303 -1.11068124 -0.86322786  1.37884826]]

[ True  True  True False  True  True  True  True]
[[-0.29328103 -0.22242053  0.54910688  0.91494522]
 [ 0.2863458  -0.05648714 -1.76886857  0.32965203]
 [ 1.45282117 -0.48131736 -0.11466913 -0.87196527]
 [ 0.24536411  0.89414005 -0.30706926  1.31847257]
 [-0.22343436  1.09889078 -0.59373514  0.68180308]
 [ 1.38830303 -1.11068124 -0.86322786  1.37884826]
 [-0.04764955 -0.31243761 -0.52817884 -0.21344169]]


In [ ]:
#비교 연산으로 특정 조건에 해당하는 값 변경
data_arr[name_arr == '명환'] = 7
print(data_arr, "\n")

#dtype이 정수나 실수인 경우, 크고 작은 비교 연산도 가능
data_arr[data_arr < 0] = 0
print(data_arr)

[[-0.29328103 -0.22242053  0.54910688  0.91494522]
 [ 7.          7.          7.          7.        ]
 [ 1.45282117 -0.48131736 -0.11466913 -0.87196527]
 [-0.48235925  0.66061707  1.16550195 -1.2294553 ]
 [ 0.24536411  0.89414005 -0.30706926  1.31847257]
 [-0.22343436  1.09889078 -0.59373514  0.68180308]
 [ 1.38830303 -1.11068124 -0.86322786  1.37884826]
 [-0.04764955 -0.31243761 -0.52817884 -0.21344169]] 

[[0.         0.         0.54910688 0.91494522]
 [7.         7.         7.         7.        ]
 [1.45282117 0.         0.         0.        ]
 [0.         0.66061707 1.16550195 0.        ]
 [0.24536411 0.89414005 0.         1.31847257]
 [0.         1.09889078 0.         0.68180308]
 [1.38830303 0.         0.         1.37884826]
 [0.         0.         0.         0.        ]]


In [ ]:
#Fancy Indexing : 정수 배열을 이용하여 행렬을 Indexing
#1차원 행령을 특정 차원으로 변경
arange_data = np.arange(32)
print(arange_data, "\n")

arange_data = arange_data.reshape((8,4))
print(arange_data, arange_data.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [ ]:
print(arange_data, "\n")
#8행 중 3번째/2번째/0번째/6번째 행을 출력
print(arange_data[[3,2,0,6]], "\n")
#8행 중 마지막/마지막에서 5번째/마지막에서 두번째/마지막 행을 출력
print(arange_data[[-1, -5, -2, -1]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 

[[12 13 14 15]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [24 25 26 27]] 

[[28 29 30 31]
 [12 13 14 15]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
print(arange_data, "\n")
#3행 1열, 2행 0열, 0행 3열, 6행 2열 출력
print(arange_data[[3,2,0,6], [1,0,3,2]], "\n")
#3행 1열이 포함된 행, 2행 0열이 포함된 행, 0행 3열이 포함된 행, 6행 2열이 포함된 행 출력
print(arange_data[[3,2,0,6]][:, [1,0,3,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 

[13  8  3 26] 

[[13 12 15 14]
 [ 9  8 11 10]
 [ 1  0  3  2]
 [25 24 27 26]]


In [ ]:
#Transpose / SwapAxes : 행과 열을 맞바꾼 전치 행렬
#2차원 행렬일 경우, 행과 열을 바꿈
#메소드 transpose는 새로운 객체 ndarray를 생성하지 않음
arange_data = np.arange(15).reshape((3, 5))
print(arange_data, "\n")
print(arange_data.T, "\n")
print(np.transpose(arange_data))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
#3차원 이상의 행렬일 경우, 바꾸고자 하는 축을 입력
#1. 2층 4행 3열의 3차원 행렬 생성
arange_data =np.arange(24).reshape((2, 4, 3))
print(arange_data)
print(arange_data.shape, "\n")

#2. 3층 2행 4열 / 2,0,1 : 원본 arange_data에서 열 / 층 / 행 값
print(np.transpose(arange_data, (2, 0, 1)))
print(np.transpose(arange_data, (2, 0, 1)).shape, "\n")

#3. 4층 3열 2행 / 1,2,0 : 원본 arange_data에서 행 / 열 / 층 값
print(np.transpose(arange_data, (1, 2, 0)))
print(np.transpose(arange_data, (1, 2, 0)).shape, "\n")

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
(2, 4, 3) 

[[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]
(3, 2, 4) 

[[[ 0 12]
  [ 1 13]
  [ 2 14]]

 [[ 3 15]
  [ 4 16]
  [ 5 17]]

 [[ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]]]
(4, 3, 2) 



In [ ]:
#예시
arange_data = np.arange(16).reshape((2,2,4)) #2층 2행 4열의 행렬 생성
print(arange_data, "\n")

print("transpose 후")
print(arange_data.transpose(1,0,2)) #2층 2행 4열 생성 > 층과 행 변경

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 

transpose 후
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [ ]:
#두 개의 축만 바꾸고 싶은 경우
aragne_data = np.arange(24).reshape((2, 4, 3))
print(arange_data, "\n")

print("층과 행 변경")
print(np.swapaxes(arange_data, 0, 1))
print(np.swapaxes(arange_data, 0, 1).shape, "\n")

print("행과 열 변경")
print(np.swapaxes(arange_data, 1, 2))
print(np.swapaxes(arange_data, 1, 2).shape, "\n")

print("층과 열 변경")
print(np.swapaxes(arange_data, 0, 2))
print(np.swapaxes(arange_data, 0, 2).shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 

층과 행 변경
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
(2, 2, 4) 

행과 열 변경
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
(2, 4, 2) 

층과 열 변경
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]
(4, 2, 2)


random - 컴퓨터 내부에서 계산된 의사난수

표준 정규 분포를 따르는 평균 0 / 분산 1 형태로 출력

In [3]:
#randn은 표준 정규 분포를 따르는 평균 0 , 분산 1 형태로 출력
import numpy as np
rand_data1 = np.random.randn()
rand_data2 = np.random.randn(10)
rand_data3 = np.random.randn(2,5)
print(rand_data1,'\n')
print(rand_data2, '\n')
print(rand_data3)

-0.146222277849422 

[-0.44642648 -0.53517165  0.71678501  1.70646448  0.7870709   0.42655827
 -0.77655943  0.23556666 -0.37649706  0.84856506] 

[[-0.52409089  0.49333531  0.85589956 -0.88525934 -0.23027916]
 [-0.73460794  0.63107693  0.46371754 -0.65150437  0.27962544]]


In [6]:
#메소드 normal은 다른 정규 확률 분포를 따르는 난수 생성 가능 - 매개변수로 평균 분산 받음
#randn/normal은 표준 정규분포를 따르기 때문세 소수점 단위의(실수형) 난수 생성
rand_data = np.random.normal(0, 1, 10)
print(rand_data, '\n')

rand_data = np.random.normal(0, 1, (2,3))
print(rand_data)

[ 0.15326544 -0.29595145  0.00719733 -0.67510987 -1.03475313  0.90536232
 -1.59444431  0.91954343  1.21371647  0.17825616] 

[[-0.78104526  0.23247635  0.1095519 ]
 [ 1.74532705  0.68241261  0.56108492]]


In [7]:
#메소드 randint는 매개변수로 low/high 사이의 정수 현태 난수 생성
rand_data = np.random.randint(2, 9, 20)
print(rand_data, '\n')

rand_data = np.random.randint(2, 9, (2,5))
print(rand_data)

[3 2 3 3 5 2 5 5 4 8 5 8 2 5 3 5 3 4 8 7] 

[[4 8 4 3 2]
 [5 6 7 6 8]]


In [17]:
#where : Numpy의 삼항 연산자(Ternary Operator) - 주로 행렬의 특정 조건에 해당하는 값만 출력
rand_data = np.random.randn(10)
print(rand_data)

#기존 파이썬 문법
result = [True if i > 0 else False for i in rand_data]
print(result)
print(type(result), '\n')

[ 0.10631046 -0.02408327 -0.18420627 -0.33980109  0.4069303  -1.53502556
  1.07154799  1.15848578 -2.67041129 -1.53822331]
[True, False, False, False, True, False, True, True, False, False]
<class 'list'> 

[ True False False False  True False  True  True False False]
<class 'numpy.ndarray'> bool


In [19]:
#메소드 where을 이용한 True/False 행렬 출력
#i는 for 반복문에서 발생한 변수로 왼쪽에는 맞는 경우 오른쪽에는 틀린 경우 출력값 입력
#결과는 리스트 형식으로 출력
result = np.where(rand_data > 0, True, False)

print(result)
print(type(result), result.dtype)

[ True False False False  True False  True  True False False]
<class 'numpy.ndarray'> bool


In [18]:
#객#메소드 where을 이용한 True / 원래 값 행렬 출력
result1 = np.where(rand_data > 0, True, rand_data)

print(result1)
print(type(result1), result1.dtype, '\n')

[ 1.         -0.02408327 -0.18420627 -0.33980109  1.         -1.53502556
  1.          1.         -2.67041129 -1.53822331]
<class 'numpy.ndarray'> float64 



In [21]:
#행렬과 통계학
rand_data = np.random.normal(0, 1, 10)
print(rand_data)

print(np.sum(rand_data))
print(np.mean(rand_data))
print(np.std(rand_data))
print(np.var(rand_data))

[-0.65370176 -1.55352402 -0.55246992  2.45927116  3.11623895  0.42934511
 -1.1101896   0.40896608 -0.47613666  0.65411159]
2.7219109154640373
0.27219109154640375
1.428381787043484
2.040274529557537


In [24]:
#다차원 행렬 분석
rand_data = np.random.randn(2,5)
print(rand_data)

#axis 지정을 통해 계산 방향 지정
print(np.sum(rand_data))
print(np.sum(rand_data, 0),'\n')
print(np.sum(rand_data, 1), '\n')

print(rand_data.mean())
print(rand_data.mean(0))
print(rand_data.mean(1))

[[ 0.17980734 -0.0418954   0.22084632 -0.46118427  0.20009965]
 [ 0.21812341 -0.42089174 -0.27746401 -1.02337189  0.81270949]]
-0.5932210896360595
[ 0.39793075 -0.46278714 -0.05661769 -1.48455616  1.01280914] 

[ 0.09767365 -0.69089474] 

-0.05932210896360594
[ 0.19896538 -0.23139357 -0.02830884 -0.74227808  0.50640457]
[ 0.01953473 -0.13817895]


In [26]:
#누적 합과 누적 곱
arange_data = np.arange(12).reshape(3,4)
print(arange_data, '\n')

print(np.cumsum(arange_data), '\n')
print(np.cumsum(arange_data, 0), '\n')
print(np.cumsum(arange_data, 1), '\n')

#누적곱
print(np.cumprod(arange_data, 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[ 0  1  3  6 10 15 21 28 36 45 55 66] 

[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]] 

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]] 

[[  0   1   2   3]
 [  0   5  12  21]
 [  0  45 120 231]]


Numpy 정렬은 오름차순 정렬만 가능

메소드 sort에서 축에 대한 매개변수 기본값은 -1

- 2차원 행 / 열 일 경우 열
- 3차원 층 / 행 / 열 일 경우 열
- 매개변수가 None이며 평탄화 후 정렬

In [27]:
rand_data = np.random.normal(0, 1, 10)
print(rand_data)
print(np.sort(rand_data))

[-0.89457722 -0.00746867 -0.19272595 -0.62752953  0.68264794  1.76586498
 -0.06420966  0.64739599 -0.81700796 -0.09552344]
[-0.89457722 -0.81700796 -0.62752953 -0.19272595 -0.09552344 -0.06420966
 -0.00746867  0.64739599  0.68264794  1.76586498]


In [28]:
rand_data = np.random.randn(3,5)
print(rand_data, '\n')
print(np.sort(rand_data),'\n')
print(np.sort(rand_data, -1), '\n')
print(np.sort(rand_data, None))

[[ 0.95464969 -0.82682105  0.87078102  0.51255814 -0.27568212]
 [-0.84110758  1.9912795   2.13096044 -1.76255382  0.74194816]
 [ 0.01874784 -1.59516228  0.47376094 -2.36552101  0.54219639]] 

[[-0.82682105 -0.27568212  0.51255814  0.87078102  0.95464969]
 [-1.76255382 -0.84110758  0.74194816  1.9912795   2.13096044]
 [-2.36552101 -1.59516228  0.01874784  0.47376094  0.54219639]] 

[[-0.82682105 -0.27568212  0.51255814  0.87078102  0.95464969]
 [-1.76255382 -0.84110758  0.74194816  1.9912795   2.13096044]
 [-2.36552101 -1.59516228  0.01874784  0.47376094  0.54219639]] 

[-2.36552101 -1.76255382 -1.59516228 -0.84110758 -0.82682105 -0.27568212
  0.01874784  0.47376094  0.51255814  0.54219639  0.74194816  0.87078102
  0.95464969  1.9912795   2.13096044]


In [30]:
#클래스 Numpy 메소드 sort는 정렬한 결과를 반환
#크랫스 ndarray 메소드 sort는 정렬한 결과를 객체에 적용
print(np.sort(rand_data))
print(rand_data)
print(rand_data.sort())
print(rand_data)

print("")
#메소드 argsort는 오름차순 순서를 알려줌, 중복된 값은 생략
print(np.argsort([8,2,9,4,2,5,2,1]))

[[-0.82682105 -0.27568212  0.51255814  0.87078102  0.95464969]
 [-1.76255382 -0.84110758  0.74194816  1.9912795   2.13096044]
 [-2.36552101 -1.59516228  0.01874784  0.47376094  0.54219639]]
[[ 0.95464969 -0.82682105  0.87078102  0.51255814 -0.27568212]
 [-0.84110758  1.9912795   2.13096044 -1.76255382  0.74194816]
 [ 0.01874784 -1.59516228  0.47376094 -2.36552101  0.54219639]]
None
[[-0.82682105 -0.27568212  0.51255814  0.87078102  0.95464969]
 [-1.76255382 -0.84110758  0.74194816  1.9912795   2.13096044]
 [-2.36552101 -1.59516228  0.01874784  0.47376094  0.54219639]]

[7 1 4 6 3 5 0 2]


In [31]:
#고유값 찾기
#메소드 randint의 2~9사이의 값은 총 7개
#20개를 추출할 경우, 확률적으로 모든 값은 2번 이상 반복
#매개변수 return_counts가 True일 경우, 해당 고유값이 몇 번 발생했는지도 반환
rand_data = np.random.randint(2, 9, 20)
print(rand_data)

#고유 값 찾기
print(np.unique(rand_data))

print(np.unique(rand_data, return_counts=True))

[4 7 7 5 8 7 2 5 6 4 4 2 6 4 6 2 6 5 5 2]
[2 4 5 6 7 8]
(array([2, 4, 5, 6, 7, 8]), array([4, 4, 4, 4, 3, 1]))


In [33]:
#행렬의 특정 값 찾기
#in1d : 행렬에서 특정 값에 해당하는 값만 True / 그 외에는 False
rand_data = np.random.randint(2, 9, 5)
print(rand_data)

print(np.in1d(rand_data, [2,3]))

[7 2 3 2 4]
[False  True  True  True False]


In [35]:
#intersect1d : 두 행렬의 교집합을 정렬해서 반환
#union1d : 두 행렬의 합집합을 정렬해서 반환
#setdiff1d : 두 행렬의 차집합을 정렬해서 반환 - 두 행렬의 순서에 따라 다른 결과가 출력될 수 있음
rand_data = np.random.randint(2, 9, (2,5))
print(rand_data, '\n')

print(np.intersect1d(rand_data[0], rand_data[1]))
print(np.union1d(rand_data[0], rand_data[1]))
print(np.setdiff1d(rand_data[0], rand_data[1]))
print(np.setdiff1d(rand_data[1], rand_data[0]))

[[5 6 7 3 8]
 [4 3 2 8 3]] 

[3 8]
[2 3 4 5 6 7 8]
[5 6 7]
[2 4]


In [36]:
#특정 조건에 부합하는 요소의 수 세기
arange_data = np.arange(1, 10)
print(arange_data)

#관행적으로 False = 0, True = 1
result = np.where(arange_data > 0, True, False).sum()
print(result)

[1 2 3 4 5 6 7 8 9]
9
