In [5]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)
print(test_array)

[1. 4. 5. 8.]


In [6]:
test_array

array([1., 4., 5., 8.])

In [7]:
type(test_array[3])

numpy.float64

In [9]:
test_array=np.array([1, 4, 5, "8"], float)
print(test_array)

[1. 4. 5. 8.]


In [10]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [11]:
print(test_array.dtype)

float64


In [12]:
print(test_array.shape)

(4,)


In [14]:
#한글로 준 경우 형변환이 안됨 => 에러 발생
test_array=np.array([1, 4, 5, "안녕"], float)
print(test_array)

ValueError: could not convert string to float: '안녕'

In [17]:
#(4,) 콤마가 있으면 tuple 없으면 int
print(type((4,)))
print(type((4)))

<class 'tuple'>
<class 'int'>


In [18]:
matrix = [[1,2,5,8],[1,2,3,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [47]:
tensor_rank3 = [
    [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,3,8],[1,2,5,8]]
]
t3 = np.array(tensor_rank3, int)
print(t3.shape, t3.ndim, t3.size)

(4, 3, 4) 3 48


In [52]:
#변형 Rank4 (2,4,3,4) 만들어보기
tensor_rank4 = [
                    [
                        [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                        [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                        [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                        [[1,2,5,8],[1,2,3,8],[1,2,5,8]]
                    ],
                    [
                        [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                        [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                        [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                        [[1,2,5,8],[1,2,3,8],[1,2,5,8]]
                    ]
                ]
t4 = np.array(tensor_rank4, int)
print(t4.shape, t4.ndim, t4.size)

(2, 4, 3, 4) 4 96


In [53]:
#변형 Rank5 (1,2,4,3,4) 만들어보기
tensor_rank5 = [
                    [
                        [
                            [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                            [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                            [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                            [[1,2,5,8],[1,2,3,8],[1,2,5,8]]
                        ],
                        [
                            [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                        [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                            [[1,2,5,8],[1,2,3,8],[1,2,5,8]],
                            [[1,2,5,8],[1,2,3,8],[1,2,5,8]]
                        ]
                    ]
                ]
t5 = np.array(tensor_rank5, int)
print(t5.shape, t5.ndim, t5.size)

(1, 2, 4, 3, 4) 5 96


In [59]:
a = np.array([[1,2,3.5],[4,5,6.5]], dtype=int)
np.round(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
b = np.array([[1,2,3.5],[4,5,6.5]], dtype=float)
np.round(b)

array([[1., 2., 4.],
       [4., 5., 6.]])

In [66]:
import sys
np.array([[1,2,3.5],[4,5,6.5]], dtype=np.float64).itemsize

8

In [67]:
import sys
np.array([[1,2,3.5],[4,5,6.5]], dtype=np.float32).itemsize

4

In [68]:
x = np.array([[1,2,5,8],[1,2,5,8]])
x.shape

(2, 4)

In [69]:
#매개변수로 -1을 입력하면 자동으로 나머지 값이 지정됨
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [70]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [77]:
#전체 데이터 요소의 개수가 맞지 않는 경우 ValueError 발생
x.reshape(2,2)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [74]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [139]:
x.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [78]:
x = np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [79]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [80]:
x = np.array([[1,2,3,], [4.5,5,6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
x[0][0]

1

In [82]:
x[0,2]

3

In [83]:
x[0,1] = 100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

In [92]:
x = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
x[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [86]:
x[1,1:3]

array([7, 8])

In [87]:
x[1:3]

array([[ 6,  7,  8,  9, 10]])

In [88]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [89]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [90]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [94]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [96]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [97]:
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [98]:
np.zeros(shape=(2,2),dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [99]:
np.empty(shape=(2,4), dtype=np.float32)

array([[ 6.4096906e-10,  6.4096906e-10, -8.6466561e-04, -4.2599473e-43],
       [ 1.3039680e+13,  6.2217652e-43,  2.8726619e-43,  0.0000000e+00]],
      dtype=float32)

In [101]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [103]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [104]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [105]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [106]:
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [108]:
np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [109]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
np.diag(matrix)

array([0, 4, 8])

In [111]:
np.diag(matrix, k=1)

array([1, 5])

In [112]:
np.random.uniform(0, 5, 10)

array([0.81704077, 4.60753513, 4.16781794, 0.26892866, 1.81578289,
       0.44362133, 0.57126591, 2.74477225, 0.03329313, 2.2520634 ])

In [113]:
np.random.normal(0,2,10)

array([ 2.3492355 ,  2.021688  , -1.47855995, -2.84482183, -1.07073322,
       -1.68650468, -0.84978056, -2.45777255,  1.28180002, -1.2930698 ])

In [114]:
import numpy as np
test_array = np.arange(1,11)
test_array.sum()

55

In [115]:
test_array=np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [117]:
test_array.sum(axis=1)

array([10, 26, 42])

In [127]:
test_array = np.arange(1,13).reshape(3,4)

third_order_tensor = np.array([test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [128]:
third_order_tensor.sum(axis=0)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [129]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24]])

In [130]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42]])

In [122]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [123]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [124]:
test_array.std()#표준편차

3.452052529534663

In [125]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [126]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [132]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack((v1,v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [135]:
v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
v1

array([[1],
       [2],
       [3]])

In [136]:
v2

array([[4],
       [5],
       [6]])

In [138]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [140]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])
np.concatenate((v1,v2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
v1 = np.array([1,2,3,4]).reshape(2,2)
v2 = np.array([[5,6]]).T
v1

array([[1, 2],
       [3, 4]])

In [149]:
v2

array([[5],
       [6]])

In [145]:
np.concatenate((v1,v2),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [154]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
print(x + x, '\n')
print(x - x, '\n')
print(x / x, '\n')
print(x * x, '\n')
print(x ** x)

[[ 2  4  6]
 [ 8 10 12]] 

[[0 0 0]
 [0 0 0]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[ 1  4  9]
 [16 25 36]] 

[[    1     4    27]
 [  256  3125 46656]]


In [156]:
x_1 = np.arange(1, 7).reshape(2,3)
x_2 = np.arange(1, 7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [158]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [159]:
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [160]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [161]:
x - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [162]:
x // 3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]], dtype=int32)

In [163]:
x ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [164]:
x = np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [166]:
v = np.arange(10, 40, 10)
v

array([10, 20, 30])

In [167]:
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [168]:
import numpy as np
x = np.array([4,3,2,6,8,5])
x > 3

array([ True, False, False,  True,  True,  True])

In [169]:
x = np.array([1,3,0])
y = np.array([2,1,7])
x > y

array([False,  True, False])

In [170]:
x = np.array([4,3,2,6,8,5])
(x>3).all()

False

In [171]:
(x>3).any()

True

In [174]:
x = np.array([4,6,7,3,2])
x > 5

array([False,  True,  True, False, False])

In [175]:
np.where(x>5)

(array([1, 2], dtype=int64),)

In [176]:
x = np.array([4,6,7,3,2])
np.where(x>5, 10, 20)

array([20, 10, 10, 20, 20])

In [177]:
x = np.array([4,6,7,3,2])
np.where(x>5, "A", "B" )

array(['B', 'A', 'A', 'B', 'B'], dtype='<U1')

In [178]:
x = np.array([4,6,7,3,2])
np.argsort(x)

array([4, 3, 0, 1, 2], dtype=int64)

In [179]:
np.argmax(x)

2

In [180]:
np.argmin(x)

4