In [1]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier

In [2]:
X = np.load('C:/Users/water/anaconda3/envs/ml/4. 인공지능/source/ch13/titanic_X_train.npy')
y = np.load('C:/Users/water/anaconda3/envs/ml/4. 인공지능/source/ch13/titanic_y_train.npy')

In [4]:
X[0]

array([0.27345609, 0.01415106, 0.        , 1.        , 0.        ,
       0.125     , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [5]:
y[:10]

array([0., 1., 1., 1., 0., 0., 0., 0., 1., 1.])

In [6]:

clf1 = LogisticRegression(random_state=1)
clf2 = DecisionTreeClassifier(random_state=1, max_depth=4)
clf3 = GaussianNB()

eclf = VotingClassifier(
    estimators=[('lr', clf1), ('rf', clf2), ('gnb',clf3)], voting='hard')

In [8]:
#cross_val_score(X 데이터, X값, y 값, cross valiation=5)
#3개의 분류기에 5등분 중 1/4로 나눈 test/train data로 학습한 결과 값의 평균 
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X, y, cv=5).mean()

0.8222941661905668

In [9]:
#각 분류기 별 평균
cross_val_score(clf1, X, y, cv=5).mean()

0.8290420872214816

In [10]:
cross_val_score(clf2, X, y, cv=5).mean()

0.8223068621849807

In [11]:
cross_val_score(clf3, X, y, cv=5).mean()

0.4600139655938551

In [14]:
#3번 분류기인 GaussianNB와는 잘 맞지 않아 빼고 성능 확인 => 정답률 증가
eclf = VotingClassifier(
    estimators=[('lr', clf1), ('rf', clf2)], voting='hard')
cross_val_score(eclf, X, y, cv=5).mean()

0.8301783787215135

In [15]:
clf1 = LogisticRegression(random_state=1)
clf2 = DecisionTreeClassifier(random_state=1)
eclf = VotingClassifier(estimators=[('lr', clf1), ('dt', clf2)], voting='hard')

In [16]:
#하이퍼 매개변수를 튜닝한 투표 분류기
c_params = [0.1, 5.0, 7.0, 10.0, 15.0, 20.0, 100.0]

params ={
    "lr__solver" :
        ['liblinear'], "lr__penalty" : ["l2"], "lr__C" : c_params,
    "dt__criterion" : ["gini", "entropy"],
    "dt__max_depth" : [10,8,7,6,5,4,3,2],
    "dt__min_samples_leaf": [1,2,3,4,5,6,7,8,9]
}

In [17]:
#GridSearchCV: 파라미터를 격자에 넣고 모든 경우를 테스트해서 좋은 결과 
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5)
grid = grid.fit(X, y)
grid.best_score_

0.8425569732749316

In [18]:
#가장 좋은 성능을 내는 매개변수 출력
grid.best_params_

{'dt__criterion': 'gini',
 'dt__max_depth': 10,
 'dt__min_samples_leaf': 5,
 'lr__C': 5.0,
 'lr__penalty': 'l2',
 'lr__solver': 'liblinear'}

In [22]:
import numpy as np

from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier

X = np.load('C:/Users/water/anaconda3/envs/ml/4. 인공지능/source/ch13/titanic_X_train.npy')
y = np.load('C:/Users/water/anaconda3/envs/ml/4. 인공지능/source/ch13/titanic_y_train.npy')
clf1 = LogisticRegression(random_state=1)
eclf = BaggingClassifier(clf1, oob_score=True)#bagging 성능 확인

from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X, y, cv=5).mean()

C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_bagging.py:706: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_bagging.py:712: RuntimeWarning: invalid value encountered in true_divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_bagging.py:706: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_bagging.py:712: RuntimeWarning: invalid value encountered in true_divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_bagging.py:706: UserWarning: 

0.8256713007046276

In [23]:
params ={
    "n_estimators" : [10,20,30,40,50,55], #분류기 개수 늘림 = 데이터 셋 많이 만듬
    "max_samples" : [0.5,0.6,0.7,0.8,0.9,1]
}

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5)
grid = grid.fit(X, y)

grid.best_score_

C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_bagging.py:706: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_bagging.py:712: RuntimeWarning: invalid value encountered in true_divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_bagging.py:706: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_bagging.py:712: RuntimeWarning: invalid value encountered in true_divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_bagging.py:706: UserWarning: 

0.8312892782327175

In [24]:
grid.best_params_

{'max_samples': 0.8, 'n_estimators': 55}

In [25]:
grid.best_estimator_.oob_score_

0.8323959505061868

In [37]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier


X = np.load('C:/Users/water/anaconda3/envs/ml/4. 인공지능/source/ch13/titanic_X_train.npy')
y = np.load('C:/Users/water/anaconda3/envs/ml/4. 인공지능/source/ch13/titanic_y_train.npy')

eclf = RandomForestClassifier(n_estimators=100, max_features=2, n_jobs=7, oob_score=True)

from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X, y, cv=5).mean()

[[0.27345609 0.01415106 0.         ... 0.         0.         0.        ]
 [0.473882   0.13913574 0.         ... 0.         0.         0.        ]
 [0.32356257 0.01546857 0.         ... 0.         0.         0.        ]
 ...
 [0.30873565 0.04577135 0.22222222 ... 0.         0.         0.        ]
 [0.32356257 0.0585561  0.         ... 0.         0.         0.        ]
 [0.39872228 0.01512699 0.         ... 0.         0.         0.        ]]


0.7941852345584968

In [31]:
from sklearn.model_selection import GridSearchCV

params ={
    "n_estimators" : [10, 20, 30, 50, 100],
    "max_features" : [1,2,3,4,5,6,7, 10, 15, 20, 25, len(X[0])]
    }

grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5)
grid = grid.fit(X, y)

grid.best_score_

C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some in

C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
C:\Users\water\anaconda3\envs\ml\lib\site-packages\sklearn\ensemble\_forest.py:560: UserWarning: Some in

0.8245540531962166

In [32]:
grid.best_params_

{'max_features': 20, 'n_estimators': 100}

In [33]:
grid.best_estimator_.oob_score_

0.8233970753655793

In [39]:
import numpy as np

X = np.load('C:/Users/water/anaconda3/envs/ml/4. 인공지능/source/ch13/titanic_X_train.npy')
y = np.load('C:/Users/water/anaconda3/envs/ml/4. 인공지능/source/ch13/titanic_y_train.npy')

In [40]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
eclf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=2), n_estimators=500)

In [41]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X, y, cv=5).mean()

0.7829492795023171

In [42]:
from sklearn.ensemble import RandomForestClassifier
eclf = RandomForestClassifier(n_estimators=500)
cross_val_score(eclf, X, y, cv=5).mean()

0.8043102901034723

In [43]:
eclf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=2),n_estimators=500)

params = {"base_estimator__criterion" : ["gini", "entropy"],
          "base_estimator__max_features" : [7,8,],
          "base_estimator__max_depth" : [1,2],
          "n_estimators": [23,24, 25, 26, 27],
          "learning_rate": [0.4, 0.45, 0.5, 0.55, 0.6]
          }

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5, n_jobs=7)
grid = grid.fit(X, y)

grid.best_score_

0.838056243255253

In [44]:
grid.best_params_

{'base_estimator__criterion': 'gini',
 'base_estimator__max_depth': 2,
 'base_estimator__max_features': 8,
 'learning_rate': 0.5,
 'n_estimators': 26}

In [45]:
grid.best_estimator_.feature_importances_

array([0.2684111 , 0.23342111, 0.04585571, 0.03972675, 0.04324684,
       0.06953469, 0.00796581, 0.02113027, 0.        , 0.00509179,
       0.        , 0.        , 0.02300183, 0.01451251, 0.0238831 ,
       0.07392832, 0.04190013, 0.01362548, 0.01842274, 0.        ,
       0.01340577, 0.        , 0.02090537, 0.01339569, 0.        ,
       0.00863496, 0.        ])