Python - numpy 실습

In [4]:
# 1차원 배열 생성
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 타입 확인
type(arr)

numpy.ndarray

In [6]:
# array의 형태(크기)를 확인 
arr.shape

(10,)

In [7]:
# array의 자료형을 확인 
arr.dtype

dtype('int32')

In [31]:
# data 리스트 데이터 생성 후 벡터화 연산
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
x = np.array(data)
x + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
# array 배열 끼리 연산
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
a + b

array([11, 22, 33])

In [14]:
#조건연산(True, False)
a == 2

array([False,  True, False])

In [28]:
# 2 x 3 배열 생성
c = np.array([[0, 1, 2], [3, 4, 5]])
print("행의 갯수 : ", len(c))
print("열의 갯수 : ", len(c[0]))

행의 갯수 :  2
열의 갯수 :  3


In [27]:
# 2 x 3 x 4 배열 생성
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])
# 인덱싱으로 배열크기 확인
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [26]:
# 배열 생성
ab = np.array([1, 2, 3])
print("차원 확인 : ", ab.ndim)
print("크기 확인 : ", ab.shape)

차원 확인 :  1
크기 확인 :  (3,)


In [37]:
# 1차원 배열 인덱싱
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [38]:
print(a[0])
print(a[-1])

0
4


In [39]:
# 2차원 배열 인덱싱
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
print(b[0, 0])
print(b[0, 1])
print(b[-1, -1])

0
1
5


In [47]:
#불리언 인덱싱
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
print(a[idx]) #idx가 True인 값 출력
print(a%2) #2로 나눈 나머지 값 출력
print(a % 2 == 0) #2로 나눈 나머지 값이 0인면 True 아니면 False 출력
print(a[a % 2 == 0]) #2로 나눈 나머지 값이 0인 값 출력

[0 2 4 6 8]
[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [49]:
#2차원 배열 슬라이싱
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
print(a[0, :]) #첫번째 행 전체 출력
print(a[1, 1:]) #두번째 행의 두번째 열부터 끝까지 출력
print(a[:2, :2]) #첫번째 행의 두번째 열, 두번째 행의 두번째 열까지 출력

[0 1 2 3]
[5 6 7]
[[0 1]
 [4 5]]


In [50]:
#정수 배열 확인
a = np.array([1, 2, 3])
a.dtype

dtype('int32')

In [51]:
# 실수 배열 확인
b = np.array([1.0, 2.0, 3.0])
b.dtype

dtype('float64')

In [52]:
# 배열에 하나라도 실수인자가 있으면 실수형
c = np.array([1, 2, 3.0])
c.dtype

dtype('float64')

In [53]:
# 정수형을 실수형으로 바꾸기
d = np.array([1, 2, 3], dtype="f")
d.dtype

dtype('float32')

In [55]:
#배열 생성 - np.zeros()
a = np.zeros(5)
a #실수형으로 생성됨

array([0., 0., 0., 0., 0.])

In [56]:
# 0으로 된 2x3 2차원 배열 생성
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
# 0으로 된 5x2 정수형 배열 생성 방법, default는 float
c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [60]:
#배열 생성 - np.ones()
d = np.ones((2, 3, 4), dtype="i8")
d #정수형으로 생성됨

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [63]:
#배열 생성 - np.arange()
e = np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# np.arange(시작, 끝(포함하지 않음), 단계간격)
f = np.arange(1, 21, 2) 
f

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [68]:
#전치연산
a = np.array([[1, 2, 3], [4, 5, 6]]) # 3x2 배열 생성
print(a, "\n")
print(a.T) # 3x2 배열을 2x3 배열로 전치


[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]]


In [70]:
#배열의 크기 변환
a = np.arange(10) #10개의 원소를 가진 1차원 배열 생성
print(a, "\n")
b = a.reshape(2,5) #reshape 매서드로 2X5 행렬로 변형
print(b)

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [80]:
#배열의 연산
x = np.arange(1, 10)
y = np.arange(11, 20)
print(x, "\n")
print(y, "\n")
z = x+y
print(z)

[1 2 3 4 5 6 7 8 9] 

[11 12 13 14 15 16 17 18 19] 

[12 14 16 18 20 22 24 26 28]


In [82]:
#스칼라 100과 x 벡터 연산
x = np.arange(10)
print(x)
print(100 * x)

[0 1 2 3 4 5 6 7 8 9]
[  0 100 200 300 400 500 600 700 800 900]


In [84]:
# 0~12까지 수열 생성 후 3x4 벡터 생성 후 스칼라 100과 x 벡터 곱하기
x = np.arange(12).reshape(3, 4)
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [90]:
#Broadcasting
x = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4], [4, 5, 6]]) # 1차원 배열 생성
y = np.arange(3) #1로 된 배열 생성
print(x, "\n")
print(y, "\n")
print(x + y, "\n") #연산하기
print(x + 1, "\n") #벡터와 스칼라 연산 

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [4 5 6]] 

[0 1 2] 

[[0 2 4]
 [1 3 5]
 [2 4 6]
 [4 6 8]] 

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [5 6 7]] 



In [97]:
#1차원 배열의 차원축소 연산
x = np.array([1, 2, 3, 4])
print(x.sum()) #전체합, ==np.sum(x)
print(x.min()) #최소값
print(x.max()) #최대값
print(x.argmin()) #최소값 위치
print(x.argmax()) #최대값 위치
print(x.mean()) #평균값
print(np.median(x)) #중앙값

10
1
4
0
3
2.5
2.5


In [99]:
#2차원 배열의 차원축소 연산
x = np.array([[1, 3], [2, 4]])
print(x.sum())
print(x.sum(axis=0)) #열 합계 구하기
print(x.sum(axis=1)) #행 합계 구하기

10
[3 7]
[4 6]


In [100]:
#numpy를 이용한 기술통계
x = np.array([18, 5, 10, 23, 19, -5, 10, 0, 0, 5, 2, 126, 8, 2, 5, 5, 15, -3, 4, -1, -20 ,8, 9, -4, 25, -12])
print(len(x)) #데이터의 개수
print(np.mean(x)) #데이터의 평균
print(np.var(x)) #데이터의 분산
print(np.std(x)) #데이터의 표준편차

26
9.76923076923077
637.9467455621302
25.257607676938253


In [101]:
# rand로 1차원 벡터 난수 발생
np.random.rand(10)

array([0.81225535, 0.76547817, 0.51995698, 0.66462104, 0.6936077 ,
       0.18520323, 0.820876  , 0.4227769 , 0.01658917, 0.73230123])

In [102]:
# rand로 2x2 벡터 난수 발생
np.random.rand(2, 2)

array([[0.5432806 , 0.70153102],
       [0.34030913, 0.32344484]])

In [103]:
# 10부터 20까지 10개 인자의 배열 생성
np.random.randint(10, 20, size=10)

array([11, 19, 15, 16, 15, 19, 19, 10, 17, 10])

In [104]:
# 10부터 20까지 3x3 벡터 생성
np.random.randint(10, 20, size=(3, 3))

array([[11, 16, 16],
       [16, 17, 11],
       [16, 17, 17]])