In [25]:
#실습 문제 1
import numpy as np

num_arr = np.arange(1, 21)
print(num_arr)
print()

num_arr = np.arange(20, 0, -1)
print(num_arr)
print()

num_arr= np.arange(1,21).reshape(5,4)
print(num_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [41]:
#실습 문제 2-1
n_arr = np.arange(0, 25).reshape(5,5)
print(n_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [28]:
#실습 문제 2-2
print("첫 원소 :", n_arr[0][0])
print("마지막 원소 :",n_arr[4][4])

첫 원소 : 0
마지막 원소 : 24


In [35]:
#실습 문제 2-3
print(n_arr[:2][:5])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [49]:
#실습 문제 2-4
print(n_arr[:3][:5]+10)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [134]:
#실습 문제 2-5
print(n_arr[:5,::2])

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


In [135]:
#실습 문제 2-6
print(n_arr[::2,::2])

[[ 0  2  4]
 [10 12 14]
 [20 22 24]]


In [163]:
#실습 문제 2-7
print(n_arr[0:2].reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [55]:
#실습 문제 3-1
np.random.seed(100)
a = np.random.rand(3,3,3)
print(a)

[[[0.54340494 0.27836939 0.42451759]
  [0.84477613 0.00471886 0.12156912]
  [0.67074908 0.82585276 0.13670659]]

 [[0.57509333 0.89132195 0.20920212]
  [0.18532822 0.10837689 0.21969749]
  [0.97862378 0.81168315 0.17194101]]

 [[0.81622475 0.27407375 0.43170418]
  [0.94002982 0.81764938 0.33611195]
  [0.17541045 0.37283205 0.00568851]]]


In [58]:
#실습 문제 3-2
print("a의 원소들 중 최댓값 :", a.max())

a의 원소들 중 최댓값 : 0.9786237847073697


In [59]:
#실습 문제 3-3
print("a의 원소들 중 최댓값의 위치 :", a.argmax())

a의 원소들 중 최댓값의 위치 : 15


In [179]:
#실습 문제 4-1
x = np.zeros((5,5))
print(x)
print()

list =[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
a = np.array(list).reshape(5,5)
print(a)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [186]:
#실습 문제 4-2
print("행렬의 행 방향 성분의 합 :")
print(a.sum(axis=1))

행렬의 행 방향 성분의 합 :
[3 2 3 2 3]


In [78]:
#실습 문제 5
a = np.arange(32).reshape(4,4,2)
a = a.flatten()
print("10번째 원소 :", a[9])
print("20번째 원소 :", a[19])

10번째 원소 : 9
20번째 원소 : 19


In [83]:
#실습 문제 6
x1 = [i for i in range(100)]
x2 = [i + np.random.randint(1,10) for i in range(100)]
x3 = [i + np.random.randint(1,50) for i in range(100)]
x4 = [i + np.random.randint(1,100) for i in range(100)]

print("x2와의 상관관계 : ",np.corrcoef(x1, x2))
print("x3와의 상관관계 : ",np.corrcoef(x1, x3))
print("x4와의 상관관계 : ",np.corrcoef(x1, x4))

#1) x1과 가장 상관관계가 높은 리스트는?
# x2 리스트

#2) x1과 가장 상관관계가 낮은 리스트는?
# x3 리스트

x2와의 상관관계 :  [[1.         0.99617509]
 [0.99617509 1.        ]]
x3와의 상관관계 :  [[1.         0.90523548]
 [0.90523548 1.        ]]
x4와의 상관관계 :  [[1.         0.72034595]
 [0.72034595 1.        ]]
